import {test, expect} from '@playwright/test';
const first = ['af_alloy','am_adam','bf_alice','bm_daniel'];
test.beforeEach(async ({page}) => {
  await page.goto('./');
  await expect(page.locator('.voice-card')).toHaveCount(54);
  await page.locator('audio').evaluate(a => a.muted = true);
});
test('catalog, filters, sorting, favorites and empty state', async ({page}) => {
  expect(await page.locator('.voice-card').evaluateAll(cards => cards.slice(0,4).map(c => c.dataset.voice))).toEqual(first);
  await page.getByLabel('Gender label', {exact:true}).selectOption('Female');
  await expect(page.locator('.voice-card')).toHaveCount(29);
  await page.getByLabel('Accent / background').selectOption('British');
  await expect(page.locator('.voice-card')).toHaveCount(4);
  await page.getByRole('button',{name:'Reset filters',exact:true}).click();
  await page.getByLabel('Preset language').selectOption('Japanese');
  await expect(page.locator('.voice-card')).toHaveCount(5);
  await page.getByRole('button',{name:'Reset filters',exact:true}).click();
  await page.getByLabel('Find a voice').fill('xyz-no-one');
  await expect(page.getByRole('heading',{name:'No one at this casting call.'})).toBeVisible();
  await expect(page.getByRole('button',{name:"I'm feeling lucky"})).toBeDisabled();
  await page.getByRole('button',{name:'Show all voices'}).click();
  await page.getByRole('button',{name:'Save Alloy (af_alloy) to favorites'}).click();
  await page.getByLabel('My favorites').check();
  await expect(page.locator('.voice-card')).toHaveCount(1);
  await page.reload();
  await page.getByLabel('My favorites').check();
  await expect(page.locator('.voice-card')).toHaveCount(1);
  await page.getByRole('button',{name:'Remove Alloy (af_alloy) from favorites'}).click();
  await expect(page.locator('.voice-card')).toHaveCount(0);
  await page.getByRole('button',{name:'Show all voices'}).click();
  await page.getByLabel('Running order').selectOption('name');
  await expect(page.locator('.voice-card').first()).toHaveAttribute('data-voice','am_adam');
  await page.getByLabel('Running order').selectOption('duration');
  const durations=await page.locator('.card-duration').allTextContents();
  const secs=durations.map(t=>{const [m,s]=t.split(' · ')[0].split(':').map(Number);return m*60+s;});
  expect(secs).toEqual([...secs].sort((a,b)=>a-b));
});
test('real audio, pause, queue advancement, next/previous and stop', async ({page}) => {
  await page.getByRole('button',{name:'Play Alloy (af_alloy)',exact:true}).click();
  await expect.poll(()=>page.locator('audio').evaluate(a=>a.currentTime)).toBeGreaterThan(0);
  await page.getByRole('button',{name:'Pause Alloy (af_alloy)',exact:true}).click();
  expect(await page.locator('audio').evaluate(a=>a.paused)).toBe(true);
  await page.getByRole('button',{name:'Play all voices',exact:true}).click();
  await expect(page.locator('#player-status')).toContainText('1 OF 54');
  await expect.poll(()=>page.locator('audio').evaluate(a=>Number.isFinite(a.duration))).toBe(true);
  await page.locator('audio').evaluate(a=>a.currentTime=a.duration-0.15);
  await expect(page.locator('#player-name')).toHaveText('Adam');
  await expect(page.locator('#player-status')).toContainText('2 OF 54');
  await page.getByRole('button',{name:'Next voice',exact:true}).click();
  await expect(page.locator('#player-name')).toHaveText('Alice');
  await page.getByRole('button',{name:'Previous voice',exact:true}).click();
  await expect(page.locator('#player-name')).toHaveText('Adam');
  await page.getByRole('button',{name:'Stop playback and close player'}).click();
  await expect(page.locator('#player-dock')).toBeHidden();
  expect(await page.locator('audio').evaluate(a=>a.paused)).toBe(true);
});
test('filtered Play All, lucky selection, queue finish and errors', async ({page}) => {
  await page.getByLabel('Find a voice').fill('bf_');
  await page.getByRole('button',{name:'Play 4 voices'}).click();
  await expect(page.locator('#player-description')).toContainText('bf_alice');
  await page.getByRole('button',{name:"I'm feeling lucky"}).click();
  await expect(page.locator('#player-description')).toContainText('bf_');
  await expect(page.locator('#player-name')).not.toHaveText('Alice');
  await page.getByLabel('Find a voice').fill('af_heart');
  await page.getByRole('button',{name:'Play 1 voice'}).click();
  await expect.poll(()=>page.locator('audio').evaluate(a=>Number.isFinite(a.duration))).toBe(true);
  await page.locator('audio').evaluate(a=>a.currentTime=a.duration-0.15);
  await expect(page.locator('#player-status')).toHaveText('AUDITION COMPLETE');
  await page.route('**/audio/am_adam.mp3', route=>route.abort());
  await page.getByRole('button',{name:'Reset filters',exact:true}).click();
  await page.getByRole('button',{name:'Play Adam (am_adam)',exact:true}).click();
  await expect(page.locator('#playback-message')).not.toBeEmpty();
});
test('mobile layout, keyboard and all recordings served', async ({page,request}) => {
  const errors=[];page.on('pageerror',error=>errors.push(error.message));
  await page.setViewportSize({width:390,height:844});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.getByRole('button',{name:'Play Alloy (af_alloy)',exact:true}).focus();
  await page.keyboard.press('Enter');
  await expect.poll(()=>page.locator('audio').evaluate(a=>a.currentTime)).toBeGreaterThan(0);
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  const catalog=await (await request.get('voices.json')).json();
  for(const voice of catalog.voices){const response=await request.get(voice.audio);expect(response.ok(),voice.id).toBe(true);expect((await response.body()).length).toBeGreaterThan(1000);}
  expect(errors).toEqual([]);
});
